const moviesData = [
 {
  vote_count: 4592,
  id: 299536,
  video: false,
  vote_average: 8.5,
  title: "Стригер",
  popularity: 160.36938,
  img: "./images/1.jpeg",
  poster_path: "../components/images/1.jpeg",
  original_language: "en",
  original_title: "Avangers: Infinity War",
  backdrop_path: "/images/1.jpeg",
  adult: false,
  overview:
  "As the Avangers and their allies have continued to protect the world from threats too large for any one hero to",
  release_date: "2018-04-25",
 },
 {
  vote_count: 1410,
  id: 401981,
  video: false,
  vote_average: 6.4,
  title: "Без меня",
  popularity: 58.167437,
  img: "./images/2.jpeg",
  poster_path: "",
  original_language: "en",
  original_title: "Red Sparrow",
  backdrop_path: "/",
  adult: false,
  overview:
  "Prima ballerina, Dominika Egorova faces a bleak and uncert",
  release_date: "2018-03-01",
 },
 {
  vote_count: 29,
  id: 493922,
  video: false,
  vote_average: 6.7,
  title: "Шазам",
  popularity: 36.91589,
  img: "./images/3.jpeg",
  poster_path: "",
  original_language: "en",
  original_title: "Hereditary",
  backdrop_path: "/",
  adult: false,
  overview:
  "Hereditary",
  release_date: "2018-06-06",
 },
 {
  vote_count: 4,
  id: 260513,
  video: false,
  vote_average: 7.5,
  title: "Брат",
  popularity: 36.91589,
  img: "./images/4.jpeg",
  poster_path: "",
  original_language: "en",
  original_title: "Increadibles 2",
  backdrop_path: "/",
  adult: false,
  overview:
  "Increadibles 2",
  release_date: "2018-06-06",
 },
 {
  vote_count: 42,
  id: 385332,
  video: false,
  vote_average: 5.6,
  title: "Шестое чувство",
  popularity: 36.91589,
  img: "./images/5.jpeg",
  poster_path: "",
  original_language: "en",
  original_title: "Terminal",
  backdrop_path: "/",
  adult: false,
  overview:
  "Terminal",
  release_date: "2018-06-06",
 },
 {
  vote_count: 173,
  id: 396806,
  video: false,
  vote_average: 5.8,
  title: "Holle",
  popularity: 36.91589,
  img: "./images/6.jpeg",
  poster_path: "",
  original_language: "en",
  original_title: "Anon",
  backdrop_path: "/",
  adult: false,
  overview:
  "Anon",
  release_date: "2018-06-06",
 },
 {
  vote_count: 41,
  id: 454619,
  video: false,
  vote_average: 5.8,
  title: "Семь",
  popularity: 36.91589,
  img: "./images/7.jpeg",
  poster_path: "",
  original_language: "en",
  original_title: "Owerboard",
  backdrop_path: "/",
  adult: false,
  overview:
  "Owerboard",
  release_date: "2018-06-06",
 },
 {
  vote_count: 21,
  id: 411135,
  video: false,
  vote_average: 5.8,
  title: "Востьмерка",
  popularity: 36.91589,
  img: "./images/8.jpeg",
  poster_path: "",
  original_language: "en",
  original_title: "Future World",
  backdrop_path: "/",
  adult: false,
  overview:
  "Future World",
  release_date: "2018-06-06",
 },
 {
  vote_count: 467,
  id: 399174,
  video: false,
  vote_average: 7.9,
  title: "Крым",
  popularity: 36.91589,
  img: "./images/9.jpeg",
  poster_path: "",
  original_language: "en",
  original_title: "Isle of Dogs",
  backdrop_path: "/",
  adult: false,
  overview:
  "Isle of Dogs",
  release_date: "2018-06-06",
 },

];


export default moviesData 
